POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{
    "password": "21e3qwdqwd2", 
    "username": "baadqw2"
}

###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhYWRxdzIiLCJpZCI6IjYxYjllZGIyZGE4M2IzNWFkNDRmZjkwYiIsImlhdCI6MTYzOTU4NTQ4Mn0.IRCq872I4IUmlVNGQhKYPCCic0w2MFnO4aaYo-IdOf4

{
    "title": "pirhit",
    "author": "shimony",
    "url": "testing u",
    "likes": 22
}
###

DELETE  http://localhost:3003/api/blogs/213 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhYWRxdzIiLCJpZCI6IjYxYjllZGIyZGE4M2IzNWFkNDRmZjkwYiIsImlhdCI6MTYzOTU4NTQ4Mn0.IRCq872I4IUmlVNGQhKYPCCic0w2MFnO4aaYo-IdOf4


